apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  -    name: mysql-secret
       literals:
        -   password=redhat
        -   userpass=prince
resources:
   -    efs-provisioner.yml
   -    role.yml
   -    storage.yml
   -    mysql.yml
   -    joomla.yml
